name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Create build directory
      run: mkdir -p build

    - name: Compile all C++ files (including subfolders)
      run: |
        set -e
        cpp_files=$(find . -name "*.cpp" -not -path "./.github/*")
        if [ -z "$cpp_files" ]; then
          echo "⚠️ No .cpp files found to compile."
          exit 0
        fi
        for file in $cpp_files; do
          echo "🔹 Compiling: $file"
          filename=$(basename "$file" .cpp)
          g++ -std=c++17 -O2 -Wall "$file" -o "build/$filename"
        done
        echo "✅ Compilation complete."

    - name: Show compiled files
      run: ls -R build || true

    - name: Optionally run a test executable
      run: |
        if [ -x build/main ]; then
          echo "🚀 Running build/main..."
          ./build/main || true
        else
          echo "ℹ️ No 'build/main' executable found (skipping run)."
        fi
