name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Create build directory
      run: mkdir -p build

    - name: Compile only full programs
      run: |
        set -e
        cpp_files=$(find . -name "*.cpp" -not -path "./.github/*")
        skip_count=0
        compile_count=0

        for file in $cpp_files; do
          # Skip LeetCode-style files (no main function)
          if ! grep -q "int main" "$file"; then
            echo "⚠️ Skipping (no main): $file"
            skip_count=$((skip_count+1))
            continue
          fi

          echo "🔹 Compiling: $file"
          filename=$(basename "$file" .cpp)
          g++ -std=c++17 -O2 -Wall "$file" -o "build/$filename"
          compile_count=$((compile_count+1))
        done

        echo "✅ Compiled $compile_count file(s), skipped $skip_count file(s)."

    - name: Show compiled files
      run: ls -R build || true
