name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up build directory
      run: mkdir -p build

    - name: Compile all C++ files
      run: |
        echo "Compiling all .cpp files..."
        g++ -std=c++17 *.cpp -o build/main || echo "No .cpp files found."

    - name: Optional: Run main if present
      run: |
        if [ -x build/main ]; then
          echo "Running build/main..."
          ./build/main || true
        else
          echo "No build/main executable to run (skipping)."
        fi
